"use strict";
const base="https://vet-helpline-development.dkjmmz6whh.workers.dev", match=location.hash.match(/^#thread=([a-f0-9]{32})\.([a-f0-9]{64})$/);
const status=document.getElementById("status"), input=document.getElementById("message"), send=document.getElementById("send");
let loading=false,pending=null;
function approvalMessage(paymentStatus) {
  if (paymentStatus === "Awaiting approval") return "Waiting for availability approval. You have not been charged. Payment will appear here once the operator accepts your question.";
  if (paymentStatus === "Declined — no charge") return "The operator is unavailable for this question. Your request was declined without payment.";
  if (paymentStatus === "Payment requested") return "Your question is ready for payment. Complete checkout before your paid response.";
  if (paymentStatus === "No payment required") return "Free Community Support — no payment is needed.";
  return "";
}
function notice(text,error=false){status.textContent=text;status.className=error?"error":"";}
async function api(method="GET",body=null){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(base+"/careline/client/threads/"+match[1]+(body?"/messages":""),{method,headers:{Authorization:"Bearer "+match[2],...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store",credentials:"omit",referrerPolicy:"no-referrer",signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||"This conversation could not load.");return data;}catch(error){if(error.name==="AbortError"||error instanceof TypeError)throw new Error("The connection was interrupted. Retry; your message stays here.");throw error;}finally{clearTimeout(timer);}}
function render(data){document.getElementById("thread").hidden=false;document.getElementById("pet").textContent=data.petName?"Your question about "+data.petName:"Your question";document.getElementById("question").textContent=data.question;document.getElementById("payment").textContent=data.service+" · "+data.paymentStatus;document.getElementById("availability").textContent=approvalMessage(data.paymentStatus);const pay=document.getElementById("pay");pay.hidden=true;if(data.paymentStatus === "Payment requested" && data.checkoutURL){const url=new URL(data.checkoutURL);if(url.origin===base&&url.pathname==="/pay"&&!url.hash&&!url.username&&!url.password){pay.href=url.href;pay.hidden=false;}}const list=document.getElementById("messages");list.replaceChildren();for(const message of data.messages){const item=document.createElement("li"),name=document.createElement("strong"),text=document.createElement("p"),time=document.createElement("time");item.className=message.sender;name.textContent=message.sender==="business"?"Paws & Whiskers Help Line":"You";text.textContent=message.text;time.dateTime=message.createdAt;time.textContent=new Date(message.createdAt).toLocaleString();item.append(name,text,time);list.append(item);}if(!data.messages.length){const item=document.createElement("li");item.textContent="Your question was received. Our reply will appear here.";list.append(item);}}
async function refresh(){if(!match||loading||document.hidden)return;loading=true;try{render(await api());notice("Conversation updated. Bookmark this private page to return.");}catch(error){notice(error.message,true);if(/no longer|invalid|unavailable/.test(error.message))document.getElementById("thread").hidden=true;}finally{loading=false;}}
document.getElementById("reply").addEventListener("submit",async event=>{event.preventDefault();const text=input.value.trim();if(!match||!text||text.length>4000||send.disabled)return;if(!pending||pending.text!==text)pending={id:crypto.randomUUID().replaceAll("-",""),text};send.disabled=true;notice("Sending…");try{render(await api("POST",pending));input.value="";pending=null;notice("Message sent. Return to this page to check for our reply.");}catch(error){notice(error.message,true);}finally{send.disabled=false;}});
document.getElementById("refresh").addEventListener("click",refresh);document.getElementById("copy").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(location.href);notice("Private link copied. Keep it safe.");}catch{notice("Bookmark this page or copy its address from your browser.");}});document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh();});window.addEventListener("hashchange",()=>location.reload());if(match){refresh();setInterval(refresh,15000);}else notice("Open the private conversation link you received after submitting your question.",true);
